query getSubjects($query: JSON!, $limit: Int!, $offset: Int!, $sort: JSON) {
  search(query: $query, offset: $offset, limit: $limit, sort: $sort) {
    items {
      ... on Journal {
        subjects
      }
    }
  }
}
