import { RepoTypes } from '$service/doaj/types/RepoTypes';
import { Journal, Organization } from '$service/generated/repoGqlTypes';

export type JournalsApiResponse = {
  publisher: Pick<Organization, '_id' | 'title'>;
} & Omit<Journal, RepoTypes | 'publisher'>;

export const mockJournalsApiResponse: JournalsApiResponse[] = [
  {
    _id: '609fc63a18232d0006584a62',
    title: 'Therapeutic Advances in Vaccines and Immunotherapy',
    publisher: {
      _id: '609fc4f218232d000658276a',
      title: 'IEEE',
    },
    alternativeTitle: null,
    onlineISSN: '2515-1363',
    printISSN: '2515-1355',
    subjects: ['Therapeutics. Pharmacology', 'Immunologic diseases'],
    url: 'https://journals.sagepub.com/home/tav',
    scope: null,
    apc: false,
    apcPrice: null,
    currency: null,
    sjrQuartile: null,
    jcrQuartile: null,
    embargo: null,
    licenseType: ['CC BY', 'CC BY-NC'],
    licenseAttribute: null,
    keywords: ['immunotherapy', 'infectious diseases', 'chronic diseases', 'cancer'],
    languages: ['English'],
    reviewProcess: ['Blind peer review'],
  },
  {
    _id: '609fc63a18232d0006584a63',
    title: 'Palliative Care',
    publisher: {
      _id: '609fc4f218232d000658276a',
      title: 'SAGE Publishing',
    },
    alternativeTitle: null,
    onlineISSN: '1178-2242',
    printISSN: null,
    subjects: ['Medicine (General)'],
    url: 'https://journals.sagepub.com/home/pcr',
    scope: null,
    apc: true,
    apcPrice: 1750,
    currency: null,
    sjrQuartile: null,
    jcrQuartile: null,
    embargo: null,
    licenseType: ['CC BY', 'CC BY-NC'],
    licenseAttribute: null,
    keywords: ['palliative care'],
    languages: ['English'],
    reviewProcess: ['Blind peer review'],
  },
  {
    _id: '609fc63a18232d0006584a64',
    title: 'Scars, Burns & Healing',
    publisher: {
      _id: '609fc4f218232d000658276a',
      title: 'SAGE Publishing',
    },
    alternativeTitle: null,
    onlineISSN: '2059-5131',
    printISSN: '1234-5678',
    subjects: [],
    url: 'http://journals.sagepub.com/home/sbh',
    scope: null,
    apc: true,
    apcPrice: 1000,
    currency: null,
    sjrQuartile: null,
    jcrQuartile: null,
    embargo: null,
    licenseType: ['CC BY', 'CC BY-NC'],
    licenseAttribute: null,
    keywords: ['scars', 'burns', 'tissue engineering', 'wound healing'],
    languages: ['English'],
    reviewProcess: ['Double blind peer review'],
  },
];
